### ISSUE TITLE
Strange sbt server does not respond 

### ISSUE THREAD

**Issue by shershen08** [playframework/play-java-rest-api-example#34]
I have sbt setup and the project starts so I get: `sbt server started at 127.0.0.1:4280`

But if I try to open localhost:4280
I get the console output:

```
Exception in thread "sbt-networkchannel-51982" [info] new client connected from: 52358
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at sbt.internal.server.NetworkChannel$$anon$1.run(NetworkChannel.scala:29)
[info] new client connected from: 52362
Got invalid chunk from client: Parse error: expected json value got G (line 1, column 1)
Got invalid chunk from client: Parse error: expected json value got H (line 1, column 1)
Got invalid chunk from client: Parse error: expected json value got C (line 1, column 1)
Got invalid chunk from client: Parse error: expected json value got U (line 1, column 1)
Got invalid chunk from client: Parse error: expected json value got U (line 1, column 1)
Got invalid chunk from client: Parse error: expected json value got A (line 1, column 1)
Got invalid chunk from client: Parse error: expected json value got D (line 1, column 1)
Got invalid chunk from client: Parse error: expected json value got A (line 1, column 1)
Got invalid chunk from client: Parse error: expected json value got A (line 1, column 1)
Got invalid chunk from client: Parse error: expected json value got C (line 1, column 1)
Got invalid chunk from client: Parse error: exhausted input
Shutting down client connection


```

**Comment by colinwahl** [comment]
I also have this issue - anyone know of a fix?

**Comment by colinwahl** [comment]
When you run `sbt.bat`, you are just running sbt, not the server.
Try typing `run` after you start `sbt.bat`, then navigate to `localhost:9000`
